### ISSUE TITLE
How to get n+1 in loop

### ISSUE THREAD

**Issue by jen-power** [jen-power/letter-looper-triangle#1]
@thomasjbradley

Hey Thomas,

I can't figure out how to set up this triangle loop. I understand that the premise is add the letter that is entered into the prompt, make a line break, and then repeat that previous line while adding the letter again — so n+1.

Is there a shorthand way to do this or do I need to write out 10 separate for loops, with each specifying how many letters are in each row, followed by a line break?

Thanks!

**Comment by thomasjbradley** [comment]
The shorthand way to do this is to use 2 for-loops—1 inside the other. Then the max iterations of the inside loop is equal to the current iteration of the outside loop.

**Comment by jen-power** [comment]
Thanks!
